## Numpy array and basics

In [5]:
import numpy as np
import time

## creating array from list

In [6]:
array_1d = np.array([1,2,3,4,5])
array_2d = np.array([[1,2,3],[4,5,6]])
print(array_1d)
print(array_2d)

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]


## list vs numpy array

In [7]:
py_list = [1, 2, 3]
np_array = np.array(py_list)
print("Python list multiplication", py_list * 2)
print("python list multiplication using np ", np_array * 2)

Python list multiplication [1, 2, 3, 1, 2, 3]
python list multiplication using np  [2 4 6]


In [8]:
start = time.time
print(start)

<built-in function time>


## Creating arrays from scratch

In [9]:
zeros = np.zeros((3, 4))
print(zeros)
ones = np.ones((2, 3))
print("array of ones \n",ones)

sevens = np.full((2,2),7)
print(sevens)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
array of ones 
 [[1. 1. 1.]
 [1. 1. 1.]]
[[7 7]
 [7 7]]


## Random in numpy

In [11]:
random = np.random.random((2, 3))
print("random array \n", random)
sequence = np.arange(0, 10, 2)
print("sequence array : \n", sequence)

random array 
 [[0.96385405 0.71570748 0.91965044]
 [0.70676489 0.01158802 0.42556838]]
sequence array : 
 [0 2 4 6 8]


## Vector , Matrix and Tensor

In [13]:
## A vector is a single row or a single column of numbers. 
# It has exactly one dimension (Axis 0). 
# You can think of it like a straight line of data points or a simple shopping list.
vector = np.array([1, 2, 3])
print("vector \n", vector)

vector 
 [1 2 3]


In [14]:
## A matrix is a grid of numbers arranged in rows and columns.
## It has two dimensions (Axis 0 for rows, Axis 1 for columns).
## Think of it like an Excel spreadsheet or a digital grayscale image (where each pixel is a row/column coordinate).
mat = np.array([[1, 2], [3, 4]])
print("matrix \n", mat)

matrix 
 [[1 2]
 [3 4]]


In [15]:
## A tensor is the umbrella term for any multi-dimensional array.
# However, in practice, developers usually say "tensor"
# when talking about arrays with three or more dimensions.

tensor = np.array([[1, 2], [3, 4], [5, 6], [7, 8]])
print("tensor \n", tensor)

tensor 
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]


## Array Properties

In [17]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print("shape \n", arr.shape)
print("dimension \n", arr.ndim)
print("size \n", arr.size)
print("Data types \n", arr.dtype)

shape 
 (2, 3)
dimension 
 2
size 
 6
Data types 
 int64


## Array reshaping

In [23]:
arr = np.arange(12)
print("original array \n", arr)
reshaped = arr.reshape((3, 4))
print("reshaped array \n", reshaped)
flattend = reshaped.flatten()
print("flattend array \n", flattend)
raveled = reshaped.ravel()
print(" raveled array \n", raveled)
transposed = arr.T
print("transposed array \n",transposed)


original array 
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
reshaped array 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
flattend array 
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
 raveled array 
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
transposed array 
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
