## Numpy array operations

In [8]:
import numpy as np

In [9]:
arr = np.arange(10)
print(arr)
print("Basic slicing",arr[2:7])
print("With step ",arr[1:8:2])
print("Nagative indexing" ,arr[-3])

[0 1 2 3 4 5 6 7 8 9]
Basic slicing [2 3 4 5 6]
With step  [1 3 5 7]
Nagative indexing 7


In [10]:
arr_2d =np.array([np.arange(5),np.arange(5),np.arange(5)])
print(arr_2d)
print("specific element ", arr_2d[1,2])
print("Entire row", arr_2d[1])
print("Entire coloum",arr_2d[:,1])

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]
specific element  2
Entire row [0 1 2 3 4]
Entire coloum [1 1 1]


## Sorting

In [11]:
unsorted = np.array([np.random.randint(1,101,size=10)])
print(unsorted)
print("Sorted array ",np.sort(unsorted))

[[44 30 47 57 83 33 66  9  9 11]]
Sorted array  [[ 9  9 11 30 33 44 47 57 66 83]]


## Filters

In [12]:
numbers = np.arange(10)
even_numbers = numbers[numbers % 2 == 0]
print(even_numbers)

[0 2 4 6 8]


## Indexing

In [13]:
indices = [0,2,4]
print(numbers[indices])

[0 2 4]


## Where

In [14]:
where_results = np.where(numbers<5)
print("less than 5 ",numbers[where_results])

less than 5  [0 1 2 3 4]


## Conditionals

In [18]:
conditionArray =np.where(numbers>5 ,"true" , "fales")
print(conditionArray)

['fales' 'fales' 'fales' 'fales' 'fales' 'fales' 'true' 'true' 'true'
 'true']


## Adding and removing data

In [22]:
arr1 =np.arange(0,3,1)
arr2= np.arange(3,6,1)
print(arr1)
print(arr2)
combined = np.concatenate((arr1,arr2))
print(combined)

[0 1 2]
[3 4 5]
[0 1 2 3 4 5]


## Compatibility test

In [23]:
a = np.array([1,2,3])
b = np.array([1,2,3,4])
c = np.array([1,2,3])
print("Compatibililty",a.shape == b.shape)

Compatibililty False


In [27]:
original = np.array([[1,2,],[2,3]])
new_row =np.array([[5,6]])
with_new_row = np.vstack((original,new_row))
print(original)
print(with_new_row)

new_col = np.array([[7],[8]])
with_new_col = np.hstack((original,new_col))
print(with_new_col)

[[1 2]
 [2 3]]
[[1 2]
 [2 3]
 [5 6]]
[[1 2 7]
 [2 3 8]]


## Deleting

In [28]:
arr = np.array([1,2,3,4,5])
deleted = np.delete(arr, 2)
print(deleted)

[1 2 4 5]
