## Numpy array operations

In [1]:
import numpy as np

In [6]:
arr = np.arange(10)
print(arr)
print("Basic slicing",arr[2:7])
print("With step ",arr[1:8:2])
print("Nagative indexing" ,arr[-3])

[0 1 2 3 4 5 6 7 8 9]
Basic slicing [2 3 4 5 6]
With step  [1 3 5 7]
Nagative indexing 7


In [12]:
arr_2d =np.array([np.arange(5),np.arange(5),np.arange(5)])
print(arr_2d)
print("specific element ", arr_2d[1,2])
print("Entire row", arr_2d[1])
print("Entire coloum",arr_2d[:,1])

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]
specific element  2
Entire row [0 1 2 3 4]
Entire coloum [1 1 1]


## Sorting

In [14]:
unsorted = np.array([np.random.randint(1,101,size=10)])
print(unsorted)
print("Sorted array ",np.sort(unsorted))

[[98 99 48 76 12 23 46 81 51  3]]
Sorted array  [[ 3 12 23 46 48 51 76 81 98 99]]
